# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Aktualizacje dla npm (Node.js)
  - package-ecosystem: "npm" 
    directory: "/" # Plik package.json znajduje się w katalogu głównym
    schedule:
      interval: "weekly"

  # Aktualizacje dla Docker
  - package-ecosystem: "docker"
    directory: "/" # Dockerfile znajduje się w katalogu głównym
    schedule:
      interval: "weekly"
